name: matrix

on: push

jobs:
  node-version:
    strategy: 
      matrix: 
        node-version: [6,8,9]
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: log node node-version
        run: node -v
      - uses: actions/setup-node@v2
        with:
          node-version: '6'
      - name: log node v 2
        run: node -v
